version: "3.8"
services:
  vueapp:
    image: vueimage
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/sec/app
    container_name: vuecontainer
    ports:
      - "3000:8080"
    environment:
      NODE_ENV: "Production"
    restart: always
